// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/messages.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_PREPREPARE    MessageType = 0
	MessageType_PREPARE       MessageType = 1
	MessageType_COMMIT        MessageType = 2
	MessageType_VIEW_CHANGE   MessageType = 3
	MessageType_NEW_VIEW      MessageType = 4
	MessageType_JOIN_REQUEST  MessageType = 5
	MessageType_JOIN_RESPONSE MessageType = 6
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0: "PREPREPARE",
		1: "PREPARE",
		2: "COMMIT",
		3: "VIEW_CHANGE",
		4: "NEW_VIEW",
		5: "JOIN_REQUEST",
		6: "JOIN_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"PREPREPARE":    0,
		"PREPARE":       1,
		"COMMIT":        2,
		"VIEW_CHANGE":   3,
		"NEW_VIEW":      4,
		"JOIN_REQUEST":  5,
		"JOIN_RESPONSE": 6,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_messages_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_messages_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

type ConsensusMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=types.MessageType" json:"type,omitempty"`
	View      uint64                 `protobuf:"varint,2,opt,name=view,proto3" json:"view,omitempty"`
	Sequence  uint64                 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Digest    []byte                 `protobuf:"bytes,4,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeId    string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Signature []byte                 `protobuf:"bytes,6,opt,name=signature,proto3" json:"signature,omitempty"`
	// Extensions for View Change
	PrePrepares   []*ConsensusMessage `protobuf:"bytes,7,rep,name=pre_prepares,json=prePrepares,proto3" json:"pre_prepares,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsensusMessage) Reset() {
	*x = ConsensusMessage{}
	mi := &file_proto_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsensusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsensusMessage) ProtoMessage() {}

func (x *ConsensusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsensusMessage.ProtoReflect.Descriptor instead.
func (*ConsensusMessage) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ConsensusMessage) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_PREPREPARE
}

func (x *ConsensusMessage) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *ConsensusMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ConsensusMessage) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *ConsensusMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ConsensusMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ConsensusMessage) GetPrePrepares() []*ConsensusMessage {
	if x != nil {
		return x.PrePrepares
	}
	return nil
}

type NodeStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	Alive         bool                   `protobuf:"varint,3,opt,name=alive,proto3" json:"alive,omitempty"`
	View          uint64                 `protobuf:"varint,4,opt,name=view,proto3" json:"view,omitempty"`
	IsLeader      bool                   `protobuf:"varint,5,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_proto_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{1}
}

func (x *NodeStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeStatus) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *NodeStatus) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

func (x *NodeStatus) GetView() uint64 {
	if x != nil {
		return x.View
	}
	return 0
}

func (x *NodeStatus) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SenderId      []byte                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	IntentHash    []byte                 `protobuf:"bytes,4,opt,name=intent_hash,json=intentHash,proto3" json:"intent_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_proto_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{2}
}

func (x *Header) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Header) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Header) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

func (x *Header) GetIntentHash() []byte {
	if x != nil {
		return x.IntentHash
	}
	return nil
}

type Envelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *Header                `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_proto_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Envelope) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type MembershipJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Port          string                 `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipJoinRequest) Reset() {
	*x = MembershipJoinRequest{}
	mi := &file_proto_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipJoinRequest) ProtoMessage() {}

func (x *MembershipJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipJoinRequest.ProtoReflect.Descriptor instead.
func (*MembershipJoinRequest) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{4}
}

func (x *MembershipJoinRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MembershipJoinRequest) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *MembershipJoinRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type MembershipJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approved      bool                   `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	Nodes         []*NodeStatus          `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	CurrentView   uint64                 `protobuf:"varint,3,opt,name=current_view,json=currentView,proto3" json:"current_view,omitempty"`
	F             uint32                 `protobuf:"varint,4,opt,name=f,proto3" json:"f,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembershipJoinResponse) Reset() {
	*x = MembershipJoinResponse{}
	mi := &file_proto_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembershipJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembershipJoinResponse) ProtoMessage() {}

func (x *MembershipJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembershipJoinResponse.ProtoReflect.Descriptor instead.
func (*MembershipJoinResponse) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{5}
}

func (x *MembershipJoinResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *MembershipJoinResponse) GetNodes() []*NodeStatus {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *MembershipJoinResponse) GetCurrentView() uint64 {
	if x != nil {
		return x.CurrentView
	}
	return 0
}

func (x *MembershipJoinResponse) GetF() uint32 {
	if x != nil {
		return x.F
	}
	return 0
}

type ClusterUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewNode       *NodeStatus            `protobuf:"bytes,1,opt,name=new_node,json=newNode,proto3" json:"new_node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterUpdate) Reset() {
	*x = ClusterUpdate{}
	mi := &file_proto_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterUpdate) ProtoMessage() {}

func (x *ClusterUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterUpdate.ProtoReflect.Descriptor instead.
func (*ClusterUpdate) Descriptor() ([]byte, []int) {
	return file_proto_messages_proto_rawDescGZIP(), []int{6}
}

func (x *ClusterUpdate) GetNewNode() *NodeStatus {
	if x != nil {
		return x.NewNode
	}
	return nil
}

var File_proto_messages_proto protoreflect.FileDescriptor

const file_proto_messages_proto_rawDesc = "" +
	"\n" +
	"\x14proto/messages.proto\x12\x05types\"\xf5\x01\n" +
	"\x10ConsensusMessage\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.types.MessageTypeR\x04type\x12\x12\n" +
	"\x04view\x18\x02 \x01(\x04R\x04view\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\x12\x16\n" +
	"\x06digest\x18\x04 \x01(\fR\x06digest\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\tsignature\x18\x06 \x01(\fR\tsignature\x12:\n" +
	"\fpre_prepares\x18\a \x03(\v2\x17.types.ConsensusMessageR\vprePrepares\"w\n" +
	"\n" +
	"NodeStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x14\n" +
	"\x05alive\x18\x03 \x01(\bR\x05alive\x12\x12\n" +
	"\x04view\x18\x04 \x01(\x04R\x04view\x12\x1b\n" +
	"\tis_leader\x18\x05 \x01(\bR\bisLeader\"|\n" +
	"\x06Header\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\fR\bsenderId\x12\x1f\n" +
	"\vintent_hash\x18\x04 \x01(\fR\n" +
	"intentHash\"i\n" +
	"\bEnvelope\x12%\n" +
	"\x06header\x18\x01 \x01(\v2\r.types.HeaderR\x06header\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"Z\n" +
	"\x15MembershipJoinRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04port\x18\x02 \x01(\tR\x04port\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"\x8e\x01\n" +
	"\x16MembershipJoinResponse\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12'\n" +
	"\x05nodes\x18\x02 \x03(\v2\x11.types.NodeStatusR\x05nodes\x12!\n" +
	"\fcurrent_view\x18\x03 \x01(\x04R\vcurrentView\x12\f\n" +
	"\x01f\x18\x04 \x01(\rR\x01f\"=\n" +
	"\rClusterUpdate\x12,\n" +
	"\bnew_node\x18\x01 \x01(\v2\x11.types.NodeStatusR\anewNode*z\n" +
	"\vMessageType\x12\x0e\n" +
	"\n" +
	"PREPREPARE\x10\x00\x12\v\n" +
	"\aPREPARE\x10\x01\x12\n" +
	"\n" +
	"\x06COMMIT\x10\x02\x12\x0f\n" +
	"\vVIEW_CHANGE\x10\x03\x12\f\n" +
	"\bNEW_VIEW\x10\x04\x12\x10\n" +
	"\fJOIN_REQUEST\x10\x05\x12\x11\n" +
	"\rJOIN_RESPONSE\x10\x06B\x15Z\x13bats/internal/typesb\x06proto3"

var (
	file_proto_messages_proto_rawDescOnce sync.Once
	file_proto_messages_proto_rawDescData []byte
)

func file_proto_messages_proto_rawDescGZIP() []byte {
	file_proto_messages_proto_rawDescOnce.Do(func() {
		file_proto_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)))
	})
	return file_proto_messages_proto_rawDescData
}

var file_proto_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_messages_proto_goTypes = []any{
	(MessageType)(0),               // 0: types.MessageType
	(*ConsensusMessage)(nil),       // 1: types.ConsensusMessage
	(*NodeStatus)(nil),             // 2: types.NodeStatus
	(*Header)(nil),                 // 3: types.Header
	(*Envelope)(nil),               // 4: types.Envelope
	(*MembershipJoinRequest)(nil),  // 5: types.MembershipJoinRequest
	(*MembershipJoinResponse)(nil), // 6: types.MembershipJoinResponse
	(*ClusterUpdate)(nil),          // 7: types.ClusterUpdate
}
var file_proto_messages_proto_depIdxs = []int32{
	0, // 0: types.ConsensusMessage.type:type_name -> types.MessageType
	1, // 1: types.ConsensusMessage.pre_prepares:type_name -> types.ConsensusMessage
	3, // 2: types.Envelope.header:type_name -> types.Header
	2, // 3: types.MembershipJoinResponse.nodes:type_name -> types.NodeStatus
	2, // 4: types.ClusterUpdate.new_node:type_name -> types.NodeStatus
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_messages_proto_init() }
func file_proto_messages_proto_init() {
	if File_proto_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_messages_proto_rawDesc), len(file_proto_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_messages_proto_goTypes,
		DependencyIndexes: file_proto_messages_proto_depIdxs,
		EnumInfos:         file_proto_messages_proto_enumTypes,
		MessageInfos:      file_proto_messages_proto_msgTypes,
	}.Build()
	File_proto_messages_proto = out.File
	file_proto_messages_proto_goTypes = nil
	file_proto_messages_proto_depIdxs = nil
}
